### ISSUE TITLE
could it support md5？

### ISSUE THREAD

**Issue by archangellcc** [gradle/gradle-checksum#1]
thanks for your plugin.

**Comment by eljobe** [comment]
@archangellcc It definitely can be enhanced to support md5 checksums. I initially didn't add it because the [md5() method from the Guava project is deprecated](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/hash/Hashing.html#md5--). However, that deprecation notice does admit that if you need to interoperate with existing systems, you should still use this deprecated method.

So, now the question is whether you would like to provide a pull request to add support? If not, I can put this on my todo list. But, if you have the interest, I'd be happy to have the help.
